openapi: "3.0.1" #todo find last version
info:
  title: Bikini bottom API
  description: API description in Markdown.
  version: 1.6.0
  contact:
    name: Ruslan Bazhenov
    email: bazhen.ruslan@gmail.com
tags:
  - name: snail
  - name: resident

paths:
  /bikini-bottom/resident/save:
    post:
      summary: save new resident
      operationId: saveResident
      tags:
        - resident
      requestBody:
        content:
          application/json:
            schema:
              $ref: "../components/bikini-bottom.yaml#/components/schemas/ResidentDtoBody"
      responses:
        "200":
          description: return saved data
          content:
            application/json:
              schema:
                $ref: "../components/bikini-bottom.yaml#/components/schemas/ResidentDto"

  /bikini-bottom/pet/snail/save:
    post:
      summary: save new snail pet
      operationId: saveSnail
      tags:
        - snail
      requestBody:
        content:
          application/json:
            schema:
              $ref: "../components/bikini-bottom.yaml#/components/schemas/SnailDto"
      responses:
        "200":
          description: return saved data
          content:
            application/json:
              schema:
                $ref: "../components/bikini-bottom.yaml#/components/schemas/SnailDto"

  /bikini-bottom/pet/snail/{id}:
    get:
      summary: get snail pet
      operationId: getSnailById
      tags:
        - snail
      parameters:
        - name: id
          description: ID of snail
          required: true
          in: path
          schema:
            $ref: "../components/shared.yaml#/components/schemas/ObjectId"
      responses:
        200:
          description: snail pet list
          content:
            application/json:
              schema:
                $ref: "../components/bikini-bottom.yaml#/components/schemas/SnailDto"

  /bikini-bottom/pet/snail/list:
    get:
      summary: get snail pet list
      operationId: listSnail
      tags:
        - snail
      responses:
        200:
          description: snail pet
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "../components/bikini-bottom.yaml#/components/schemas/SnailDto"